Add desktop-version to portfolio
luisrpavanelli/Portfolio-Project pull request #6
Opened 2023-02-22 22:09 UTC by luisrpavanelli

Hello, I worked in this PR to add modifies in files html and css, and also add new background images

Desktop Version:
- Create a new branch
- Change html files
- Change css files
- Add backgrounds images

2023-02-22 23:55 UTC, mckent05 requested changes
Hi @luisrpavanelli, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
- Your contact form is not designed as it is in the Figma design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏
Your project:
-- Please ensure all texts and form inputs in this section are aligned as they are in the figma template
-- Please ensure that the background images in this section are visible.
<img width="947" alt="tnsthset" src="https://user-images.githubusercontent.com/73607512/220790663-0f615f58-bcdd-4206-978d-676abac3ced6.PNG">
Figma design:
<img width="541" alt="wwrvsdd" src="https://user-images.githubusercontent.com/73607512/220790694-46efbc56-87cc-45a3-a17a-bf5885e80d7c.PNG">


_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 23:55 UTC, mckent05 commented on style.css
> +  border-radius: 8px;
- This section of your page doesn't exactly look like the Figma design template, Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your project:
-- The cards in this section should be aligned in a column of 3 and 2 rows. Please fix this 👍 👍 
-- For each of the cards, the image should come first before the other texts or details, please fix this 👍 
-- The text `My Recent Works` should be aligned in the center. Please fix this 😄 
<img width="948" alt="ryjdryjryj" src="https://user-images.githubusercontent.com/73607512/220788203-0cd0dea8-bc80-49cc-8442-e5737575c002.PNG">
Figma template:
<img width="526" alt="wefefe" src="https://user-images.githubusercontent.com/73607512/220788514-4de1b738-8b8d-492f-b266-985a117e4eae.PNG">

2023-02-22 23:55 UTC, mckent05 commented on style.css
> +  padding: 12px;
- This part of your portfolio does not look exactly like the given design template. Please fix this 😄 

Your project:
-- The section header i.e `About Me` text, section text and `Get Resume` button should be aligned in the center. Please fix this 🙏 
-- The background images for this section are missing, please fix this 🙏 
-- The technology cards are not designed the way they are in the Figma template, please include some spacing between the cards 👍 
<img width="943" alt="eetrhethse" src="https://user-images.githubusercontent.com/73607512/220789406-0ddb192a-78a8-4c91-be87-7532e2666193.PNG">

Figma template:
<img width="544" alt="eargaerg" src="https://user-images.githubusercontent.com/73607512/220789443-39d138e5-9d2c-41c6-ad96-52ad1d0f175d.PNG">

2023-02-23 18:44 UTC, luisrpavanelli commented
Hello, I worked in this PR to add modifies in files HTML and CSS, and also add folders, new background images and icons...

Desktop Version:

- Create a new branch
- Modify HTML files Mobile to Desktop Version
- Modify CSS files Mobile to Desktop Version
- Add Backgrounds Images and Icons
- Add Folders Desktop Image and Desktop Icons

2023-02-23 19:13 UTC, Shisui6 requested changes
Hi @luisrpavanelli, 

# Requires Changes 🍀
Great work on making the changes requested by a previous reviewer 👍
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet🪲.


 ## Highlights
 - Good design ✅
 - Good use of media queries ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 19:13 UTC, Shisui6 commented on style.css
> -}
Great job redesigning the contact section, as suggested by the previous reviewer👍. However, you forgot to add the background image. Please add it, so it matches the figma template better🙏.

Your design:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/37116322/221005588-dbe14aa9-d869-4f9a-badf-c6fd56d996b3.png">

Figma design:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/37116322/221005716-42826d70-f8df-473e-9c1c-327908e40c64.png">

2023-02-23 19:24 UTC, luisrpavanelli commented
Hello, I worked in this PR to add modifies in files HTML and CSS, and also add folders, new background images and icons...

Desktop Version:

Create a new branch
Modify HTML files Mobile to Desktop Version
Modify CSS files Mobile to Desktop Version
Add Backgrounds Images and Icons
Add Folders Desktop Image and Desktop Icons

Changes:

- Reduce the font size to match the figma template. 
- Add the background image to matches the figma template.

2023-02-23 19:41 UTC, Zuhaib042 approved these changes
Hi @luisrpavanelli , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approve](https://media.giphy.com/media/2N3RlyAbN20e8QRqPA/giphy.gif)
## Highlights
✅ Correct Github flow
✅ Good implementation of suggested changes
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 22:25 UTC, merged